/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e0e3e5",
        "surface-variant": "#d3e4fe",
        "primary-container": "#2170e4",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#213145",
        primary: "#0058be",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#d5e0f8",
        surface: "#f8f9ff",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-container": "#586377",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#bcc7de",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#444749",
        "tertiary-container": "#727577",
        error: "#ba1a1a",
        background: "#f8f9ff",
        "surface-container": "#e5eeff",
        outline: "#727785",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-fixed": "#191c1e",
        "inverse-primary": "#adc6ff",
        "on-primary-container": "#fefcff",
        "on-surface": "#0b1c30",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fbfdff",
        "surface-container-highest": "#d3e4fe",
        tertiary: "#595c5e",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "surface-container-high": "#dce9ff",
        "surface-tint": "#005ac2",
        secondary: "#545f73",
        "on-secondary": "#ffffff",
        "outline-variant": "#c2c6d6",
        "on-surface-variant": "#424754",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary": "#ffffff",
        "on-background": "#0b1c30",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "sidebar-width": "280px",
        "margin-page": "24px",
        "toolbar-height": "48px",
        unit: "4px",
      },
      fontFamily: {
        "headline-lg": ["Sora"],
        "body-md": ["Inter"],
        "headline-md": ["Sora"],
        "body-sm": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "utility-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "utility-mono": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
